- 
  name: Install docker and make sure its enable
  hosts: all
  become: yes
  tasks:


    - name: Install docker
      apt:
        name: docker.io
        state: latest
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Start and enable docker
      service:
        name: docker
        state: started
        enabled: yes 
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  
