- 
  name: Install Nigix and make sure its enable
  hosts: ansible_servers
  become: yes
  tasks:


    - name: Install Nginx
      apt:
        name: nginx
        state: latest
        

    - name: Start and enable Nginix
      service:
        name: nginx
        state: started
        enabled: yes  
  
